### ISSUE TITLE
Maybe intercepts DialContext is not a good choice?

### ISSUE THREAD

**Issue by fovecifer** [markdingo/cslb#1]
I am looking for a client-side load balancer recently.
Actually I did not know the best practice how to implement this.
Your cslb "hack" the DialContext func, which make net.Conn, but as I know the DefaultTransport will
"cache" or "reuse" the net.Conn created by DialContext. 
Some http server prefer connection reuse, but some not.
So the Weight of target in SRV record maybe not correct?
If the 2 targets have the same weight, but the cslb could not guarantee the target server receive same number of requests?

**Comment by markdingo** [comment]
I think you might be reading too much into the semantics of SRV.

Given that we don't know the behaviour of clients, weight really is just a general hint that hopefully averages out to be correct over time. For example, if one application submits very intensive HTTP requests, should that be taken into account compared to an application which submits very light-weight requests? How do we include the cost of different requests into the 'weight' calculation?

Alternatively, if all clients perform identically, then they will both cache and reuse the net.Conn in the same way, perfectly matching the desired weight.

I'm interested in knowing what you think should be done about the imperfections of SRV semantics - including with caching behaviour - but I do wonder whether trying to infer the cost of the applications is getting a bit beyond the knowledge of a load-balancer. 

If the suggestion is to make it impossible for the application to cache/reuse the net.Conn that could severely impact the current performance of the application and I don't really want to modify any underlying behaviour that the application make expect or rely on.

So, what do you suggest?

**Comment by fovecifer** [comment]
thanks for your response.

I use Nginx a lot, it is a good server-side load balancer, and I like the "Smooth weighted round robin algorithm".
The weight of upstream in Nginx is "correct" all the time, and in my use case I think the weight is import too.

So my choice is wrapping the "DefaultTransport", I replace the "Host" in http.Request.URL in RoundTrip interface.

I am still learning from the good open source project like your cslb, Nginx and traefik. I am trying to find out 
the best practice to implement client-side load balancer in production env. So I just share my choice with 
you, I wish this could help you.

**Comment by fovecifer** [comment]
by the way, cache/reuse the net.Conn is very import for both client and server, we should guarantee this behavior all the time.

**Comment by markdingo** [comment]
> by the way, cache/reuse the net.Conn is very import for both client and server, we should guarantee this behavior all the time.

Hi. It's worth noting that the replacement cslb.dialContext performs exactly the same as the standard dialContext and merely returns the net.Conn to the caller - in this case the http package. From that point on, it's up to the caller to cache/reuse net.Conn, the cslb package is not involved after that.

The only way for cslb to get involved at that point would be to somehow intercept the client requests and that is getting way too interventionist and is really trying to second-guess what the application and server want.

So to answer your point, cslb can't guarantee behavior because it's client code and http package code which makes those choices.

**Comment by markdingo** [comment]
> I am trying to find out
> the best practice to implement client-side load balancer in production env. So I just share my choice with
> you, I wish this could help you.

Fair enough. I think you might find that it's a decidedly tricky problem to generalise as each deployment may have different rules for how they deal with overloaded servers, or applications which tend to make very "heavy" requests. That's why cslb has a built-in "active" mode where it can actively monitor a "health-check" or "current load" to truly find out the state of the servers. You might want to experiment with that aspect and let me know whether that helps or not.
